import type { Metadata } from "next";
import Header from "@/components/header";
import { Saira } from "next/font/google";
import Provider from "@/util/providers";
import "./globals.css";

const saira = Saira({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${saira.className}`}>
        <Header />
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
